config/routes.rb
Chicoplusplus::Application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, :path => 'account', :controllers => {:registrations => 'registrations'}

  resources :inquiries, :only => [:new, :create]
  resources :topics do
    member do
      match 'vote/:direction' => 'topics#vote', :as => 'vote'
    end
  end

  match 'privacy' => 'home#privacy'
  match 'terms' => 'home#terms'
  match 'about' => 'home#about'

  root :to => 'home#index'
  get "home/index"
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  # Relationships
  belongs_to :user
  has_many :votes

  # Validations
  validates :name, :presence => true

  def refresh_vote_count
    self.num_votes = self.votes.sum(:value)
    self.save
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  # Cancan authorization
  authorize_resource :except => [:vote]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.order('num_votes desc, created_at desc').all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @topics }
    end
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @topic = Topic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/new
  # GET /topics/new.json
  def new
    @topic = Topic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(permitted_params.topic)
    @topic.user = current_user

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render json: @topic, status: :created, location: @topic }
      else
        format.html { render action: "new" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /topics/1
  # PUT /topics/1.json
  def update
    @topic = Topic.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(permitted_params.topic)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to topics_url }
      format.json { head :no_content }
    end
  end

  # POST /topics/1/vote
  def vote
    # Lookup topic (and vote, if it exists)
    @topic = Topic.find(params[:id])
    @vote = Vote.find_by_topic_id_and_user_id(@topic.id, current_user.id)
    value = params[:direction] == 'up' ? 1 : -1

    # Create/update vote
    if @vote
      @vote.value = value
      @vote.save!
    else
      @vote = Vote.new
      @vote.user = current_user
      @vote.topic = @topic
      @vote.value = value
      @vote.save!
    end

    # Refresh vote count
    @topic.reload

    # Respond with some js to update page
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_details.html.erb
<div class="topic">
  <div class="row">
    <div class="small-1 large-1 columns vote">
      <p><%= link_to raw('<i class="icon-sort-up"></i>'), vote_topic_path(topic, :direction => 'up'), :remote => true %></p>
      <p class="vote_count" id="num_votes_<%= topic.id %>"><%= topic.num_votes %></p>
      <p><%= link_to raw('<i class="icon-sort-down"></i>'), vote_topic_path(topic, :direction => 'down'), :remote => true %></p>
    </div>
    <div class="small-8 large-9 columns">
      <h4><%= link_to topic.name, topic_path(topic) %></h4>
      <div class="expander">
        <%= markdown topic.description %>
      </div>
    </div>
    <div class="small-3 large-2 columns">
      <% if topic.user.avatar? %>
        <%= image_tag topic.user.avatar.thumb.url %>
      <% else %>
        <p>Proposed by <%= topic.user.full_name %></p>
      <% end %>
    </div>
  </div>

</div>

app/views/topics/_form.html.erb
<%= simple_form_for(@topic) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, :label => 'Summary', :hint => 'Enter a quick summary of the topic you are interested in. (e.g. Backbone.js)' %>
    <%= f.input :description, :label => 'Details', :hint => 'Please be more specific about what you want to explore.', :input_html => {:rows => 10} %>
  </div>

  <div class="actions">
    <% if @topic.persisted? && can?(:destroy, @topic) %> 
      <%= link_to 'Delete Topic', @topic, :title => 'Delete', :class => 'right alert tiny button', :method => :delete, :data => { :confirm => 'Are you sure?' } %>
    <% end %>
    <%= f.submit 'Save Changes', :class => 'button' %> <span class="cancel-link">or <%= link_to 'cancel', @topic.persisted? ? @topic : topics_path %></span>
  </div>

<% end %>

app/views/topics/edit.html.erb
<h1>Edit topic</h1>
<%= render 'form' %>

app/views/topics/index.html.erb
<div class="row">
  <div class="small-6 columns">
    <h2>Topics</h2>
  </div>
  <div class="small-6 columns">
    <%= link_to('New Topic', new_topic_path, :class => 'button right') if can?(:create, Topic) %>
  </div>
</div>

<% if @topics.size > 0 %>
  <% @topics.each do |topic| %>
    <%= render :partial => 'details', :locals => {:topic => topic} %>
  <% end %>
<% else %>
  <p>No topics found. <%= link_to 'Propose one!', new_topic_path %></p>
<% end %>

app/views/topics/new.html.erb
<h1>New topic</h1>
<%= render 'form' %>

app/views/topics/show.html.erb
<p><%= link_to raw('&laquo; Back to topics'), topics_path %></p>
<%= render :partial => 'details', :locals => {:topic => @topic} %>

<% if can?(:update, @topic) %> 
<p>
  <%= link_to 'Edit', edit_topic_path(@topic), :class => 'button small' %>
  <span class="cancel-link">or <%= link_to 'cancel', topics_path %></span>
</p>
<% end %>

app/views/topics/vote.js.erb
$("#num_votes_<%= @topic.id %>").html("<%= @topic.num_votes %>");