config/routes.rb
Chicoplusplus::Application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, :path => 'account', :controllers => {:registrations => 'registrations'}

  resources :inquiries, :only => [:new, :create]
  resources :topics do
    member do
      match 'vote/:direction' => 'topics#vote', :as => 'vote'
    end
  end

  match 'privacy' => 'home#privacy'
  match 'terms' => 'home#terms'
  match 'about' => 'home#about'

  root :to => 'home#index'
  get "home/index"
end

app/models/inquiry.rb
class Inquiry < MailForm::Base
  attributes :email, :name, :subject, :body
  validates :name, :subject, :body, :presence => true
  validates :email, :presence => true, :email => true
  append :remote_ip, :user_agent

  def headers
    {
      :from => Rails.application.config.technical_sender_email,
      :to => Rails.application.config.nontechnical_recipient_email,
      :subject => "New inquiry from website"
    }
  end
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  skip_before_filter :authenticate_user!

  def new
    @inquiry = Inquiry.new
  end
  
  def create
    @inquiry = Inquiry.new(params[:inquiry])
    @inquiry.request = request
  
    if @inquiry.valid?
      @inquiry.deliver
      redirect_to(new_inquiry_path, :notice => "Thanks for reaching out. We'll get back to you shortly.")
    else
      flash.now.alert = "There was a problem with the information you submitted."
      render :new
    end
  end
  
end

app/views/inquiries/new.html.erb
<div class="row">
  <div class="small-12 large-8 columns large-centered">
    <h2>Contact Us</h2>
    <p>
      We'd love to hear your comments, suggestions, bug reports, or praise! Thanks for taking the time to help
      us improve the app!
    </p>
    <%= simple_form_for(@inquiry, :url => inquiries_path) do |f| %>
      <%= f.input :name, :label => 'Your name', :required => true %>
      <%= f.input :email, :label => 'Your email address', :required => true %>
      <%= f.input :subject, :required => true %>
      <%= f.input :body, :label => 'Message', :as => :text, :input_html => {:rows => 6} %>

      <div class="form-actions">
        <%= f.submit 'Send Message', :class => 'button' %>
      </div>
    <% end %>
  </div>
</div>