config/routes.rb
Chicoplusplus::Application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, :path => 'account', :controllers => {:registrations => 'registrations'}

  resources :inquiries, :only => [:new, :create]
  resources :topics do
    member do
      match 'vote/:direction' => 'topics#vote', :as => 'vote'
    end
  end

  match 'privacy' => 'home#privacy'
  match 'terms' => 'home#terms'
  match 'about' => 'home#about'

  root :to => 'home#index'
  get "home/index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
  <head>
    <meta charset="UTF-8">
    <meta name="description" content="" />
    <meta name="copyright" content="" />
    <link type="text/plain" rel="author" href="/humans.txt" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="HandheldFriendly" content="True" />
    <meta name="MobileOptimized" content="320" />
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">

    <meta http-equiv="cleartype" content="on">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>Chico++<%= content_for?(:title) ? " &mdash; " + yield(:title) : "" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= controller_stylesheet %>
    <%= yield :stylesheets %>

    <% if content_for? :styles %>
      <style type="text/css">
        <%= yield :styles %>
      </style>
    <% end %>
    
    <%= javascript_include_tag "vendor/custom.modernizr" %>

    <%= yield :head %>
  </head>
  <body>

    <!-- Logo & Top Nav -->
    <div class="row">
      <div class="small-6 large-3 columns logo">
        <h2><%= link_to 'Chico++', root_path %></h2>
      </div>
      <div class="small-6 large-9 columns">
        <ul class="inline-list right auth-nav">
          <% if user_signed_in? %>
            <li>Welcome, <%= current_user.first_name %>!</li>
            <li><%= link_to 'My Account', edit_user_registration_path %></li>
            <li><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %></li>
          <% else %>
            <li><%= link_to 'Sign In', new_user_session_path %></li>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <% end %>
        </ul>
        <div id="ajax_spinner" class="clear right">
          <%= image_tag('ajax-spinner.gif', :size => '32x32') %>
          <i class="icon-ok-circle">&nbsp;</i>
        </div>
      </div>
    </div>

    <!-- Errors, alerts, warnings -->
    <div class="row" id="flashes" style="display:none">
      <%= render :partial => '/shared/flashes' %>
    </div>

    <!-- Extra body elements that need to break out of the page container -->
    <%= yield :before_page %>

    <!-- Main page container -->
    <div class="row">
      <div class="small-12 columns">
        <div class="page">
          <%= yield %>
        </div>
      </div>
    </div>

    <!-- Extra body elements that need to break out of the page container -->
    <%= yield :after_page %>

    <!-- Footer -->
    <footer class="row">
      <div class="small-12 columns">
        <ul class="inline-list">
          <li><%= link_to 'Contact', new_inquiry_path %></li>
          <li><%= link_to 'About', about_path %></li>
          <li><%= link_to 'Privacy', privacy_path %></li>
          <li><%= link_to 'Terms', terms_path %></li>
        </ul>
      </div>
    </footer>

    <!--[if lt IE 8]>
    <div id="ie-warning-overlay">
      <div id="ie-warning">
        <h1>Did you know that your copy of Internet Explorer is out of date?</h1>
        <p>
          To get the best possible experience using our website, we recommend that you upgrade to the latest version or use another web browser. 
          Any of the following will provide a superior experience, not only on this site, but across the web.
        </p>
        <p>Just click one of the icons below to get to the download page.</p>
        <ul>
          <li>
            <a href="http://microsoft.com/ie">
              <%= image_tag 'browser_ie.gif', :alt => "Download Internet Explorer" %>
              <p>Internet Explorer 8+</p>
            </a>
          </li>
          <li>
            <a href="http://mozilla.org/firefox">
              <%= image_tag 'browser_firefox.gif', :alt => "Download Firefox" %>
              <p>Firefox</p>
            </a>
          </li>
          <li>
            <a href="http://google.com/chrome">
              <%= image_tag 'browser_chrome.gif', :alt => "Download Chrome" %>
              <p>Google Chrome</p>
            </a>
          </li>
          <li>
            <a href="http://apple.com/safari">
              <%= image_tag 'browser_safari.gif', :alt => "Download Safari" %>
              <p>Safari</p>
            </a>
          </li>
          <li>
            <a href="http://opera.com">
              <%= image_tag 'browser_opera.gif', :alt => "Download Opera" %>
              <p>Opera</p>
            </a>
          </li>
        </ul>
      </div>
    </div>
    <![endif]-->

    <!-- Javascript -->
    <%= javascript_include_tag "application" %>
    <%= controller_javascript %>
    <%= yield :javascripts %>

    <script type="text/javascript">
      $(document).ready(function () {
        <%= yield :onready %>
      });

      <% if !Rails.application.config.google_analytics_tracking_code.blank? %>
        var _gaq=[['_setAccount','<%= Rails.application.config.google_analytics_tracking_code %>'],['_trackPageview']];
        (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';s.parentNode.insertBefore(g,s)}(document,'script'));
      <% end %>
    </script>

  </body>
</html>